### ISSUE TITLE
虚拟测试环境中，docker 启动容器时出错

### ISSUE THREAD

**Issue by 866666** [0xaww/awd-submit-flag#1]
exec /start.sh: no such file or directory

看了下日志，应该是COPY ./start.sh /start.sh # buildkit 这句执行失败了

**Comment by 0xaww** [comment]
我这里调试是没问题的，cd 到env_test文件夹，然后运行docker-compose up -d，就能够构建了

**Comment by 866666** [comment]
我在win11 下使用的docker desktop，构建最后一步提示exec /start.sh: no such file or directory  无法启动，有没有可能是win和Linux 下编码问题

**Comment by 866666** [comment]
解决了 确实是win和Linux  平台文件格式问题
用vim打开该start.sh文件，输入：

:set ff

回车，显示fileformat=dos，重新设置下文件格式：
:set ff=unix

保存退出:

:wq

再重新构建，就可以了
